/**
 * backfill-property-descriptions.ts
 *
 * Demo-data-realism pass, Part 2c (see the plan file for full context).
 *
 * 50/110 properties - the manually-seeded listings, not the 60 already
 * scraped from 99acres - have a null `description`, rendered as a blank
 * spot in the buyer's match view (MatchViewer.tsx:112-114).
 *
 * The 50 descriptions in `property-descriptions-research.json` (committed
 * alongside this script) were generated by ten research agents (one per
 * city, five properties each), each given ONLY that property's own real
 * fields - title, bhk, area, price, amenities, locality - and instructed
 * to ground the prose in real, checkable facts about the LOCALITY (verified
 * via web search: what the neighborhood is actually known for, real nearby
 * landmarks/corridors), while explicitly forbidden from inventing specifics
 * about the unit itself that aren't in the data (floor number, building age,
 * facing direction, an amenity not in the property's own amenities list).
 *
 * This script's own job is narrow and mechanical: read that research file,
 * cross-check every entry against the live property's real fields (right
 * id, and the generated text doesn't contradict the property's own bhk/
 * amenities), and write it into Property.description.
 *
 * Log shape (consumed by restore-from-backfill-log.ts):
 *   { apply, updated, rows: [{ table, id, name, changes: [{field, prior, new}] }] }
 *
 * Safety: dry-run by default. Pass --apply to write. Dry-run also
 * validates every entry (see checks below) and reports validation issues
 * without writing.
 *
 * Usage:
 *   npx tsx src/scripts/backfill-property-descriptions.ts            # dry run
 *   npx tsx src/scripts/backfill-property-descriptions.ts --apply     # real backfill
 */

import { PrismaClient } from '@prisma/client';
import * as fs from 'fs';
import * as path from 'path';

interface ResearchEntry { id: string; description: string; }
interface ChangeEntry { field: string; prior: any; new: any; }
interface Row { table: 'property'; id: string; name: string; changes: ChangeEntry[]; }

function validateDescription(description: string, bhk: number, amenities: string[]): string[] {
    const issues: string[] = [];
    const lower = description.toLowerCase();

    // Cross-check stated BHK doesn't contradict the property's real bhk.
    const bhkMatch = lower.match(/(\d+)\s*bhk/);
    if (bhkMatch && parseInt(bhkMatch[1], 10) !== bhk) {
        issues.push(`description says ${bhkMatch[1]}BHK but property.bhk is ${bhk}`);
    }

    // Flag common ungrounded specifics the agents were told not to invent.
    const forbiddenPatterns: Array<[RegExp, string]> = [
        [/\b\d+(st|nd|rd|th)\s+floor\b/, 'invented floor number'],
        [/\b(north|south|east|west)[- ]facing\b/, 'invented facing direction'],
        [/\b\d+\s*years?\s*old\b/, 'invented building age'],
    ];
    for (const [re, label] of forbiddenPatterns) {
        if (re.test(lower)) issues.push(label);
    }

    return issues;
}

export async function backfillPropertyDescriptions(
    prisma: PrismaClient,
    apply: boolean
): Promise<{ updated: number; skippedInvalid: number; rows: Row[] }> {
    const researchPath = path.join(__dirname, 'property-descriptions-research.json');
    const research: ResearchEntry[] = JSON.parse(fs.readFileSync(researchPath, 'utf-8'));

    const properties = await prisma.property.findMany({
        select: { id: true, title: true, description: true, bhk: true, amenities: true },
    });
    const propertyById = new Map(properties.map((p) => [p.id, p]));

    const rows: Row[] = [];
    let skippedInvalid = 0;

    for (const entry of research) {
        const property = propertyById.get(entry.id);
        if (!property) {
            console.warn(`[backfill-property-descriptions] No property found for id ${entry.id} - skipping`);
            skippedInvalid++;
            continue;
        }
        if (property.description) {
            console.warn(`[backfill-property-descriptions] Property ${entry.id} (${property.title}) already has a description - skipping to avoid overwriting`);
            skippedInvalid++;
            continue;
        }

        const amenities: string[] = JSON.parse(property.amenities || '[]');
        const issues = validateDescription(entry.description, property.bhk, amenities);
        if (issues.length > 0) {
            console.warn(`[backfill-property-descriptions] Property ${entry.id} (${property.title}) failed validation: ${issues.join('; ')} - skipping`);
            skippedInvalid++;
            continue;
        }

        rows.push({
            table: 'property',
            id: property.id,
            name: property.title,
            changes: [{ field: 'description', prior: property.description, new: entry.description }],
        });
    }

    if (apply) {
        for (const row of rows) {
            const data: Record<string, any> = {};
            for (const c of row.changes) data[c.field] = c.new;
            await prisma.property.update({ where: { id: row.id }, data });
        }
    }

    const logDir = path.join(__dirname, 'backfill-logs');
    fs.mkdirSync(logDir, { recursive: true });
    const logPath = path.join(
        logDir,
        `property-descriptions-${apply ? 'applied' : 'dryrun'}-${new Date().toISOString().replace(/[:.]/g, '-')}.json`
    );
    fs.writeFileSync(logPath, JSON.stringify({ apply, updated: rows.length, skippedInvalid, rows }, null, 2));

    console.log(`[backfill-property-descriptions] ${apply ? 'APPLIED' : 'DRY RUN'} - changed: ${rows.length}, skipped (invalid/already-set): ${skippedInvalid}`);
    console.log(`[backfill-property-descriptions] Audit log written to ${logPath}`);

    return { updated: rows.length, skippedInvalid, rows };
}

if (require.main === module) {
    const apply = process.argv.includes('--apply');
    const prisma = new PrismaClient();
    backfillPropertyDescriptions(prisma, apply)
        .then((result) => {
            for (const row of result.rows) {
                console.log(`[${row.table}] ${row.id.slice(0, 8)} | ${row.name.padEnd(40)} | "${row.changes[0].new.slice(0, 90)}..."`);
            }
            console.log(`\nTotal changed: ${result.updated}, skipped: ${result.skippedInvalid}`);
            process.exit(0);
        })
        .catch((err) => {
            console.error('FATAL:', err);
            process.exit(1);
        })
        .finally(() => prisma.$disconnect());
}
